apiVersion: v1
kind: Service
metadata:
  name: fnm-mock
  labels:
    app: fnm-mock
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: fnm-mock
    tier: frontend